### ISSUE TITLE
Resources can‘t get

### ISSUE THREAD

**Issue by Gumplefik** [goodrain/builder#4]
download_buildpack https://github.com/goodrain/heroku-buildpack-go-1.git               master
download_buildpack https://github.com/goodrain/heroku-buildpack-php-1.git              master
download_buildpack https://github.com/goodrain/heroku-buildpack-python-1.git           master
download_buildpack https://github.com/goodrain/heroku-buildpack-nodejs-1.git           master

Path：builder/install-buildpacks
For branch master
https://github.com/goodrain/heroku-buildpack-go-1.git    =>   https://github.com/goodrain/heroku-buildpack-go.git 

--------------------------------------------------------------------------------------
master分支代码打包成docker image后测试使用报错，
 Unable to select a buildpack

**Comment by ysicing** [comment]
@Gumplefik 
抱歉调整支持新版，部分buildpack已经调整，如果有提示无法下载可以将对应的地址修改为 heroku-buildpack-<类型>-backports或者参考5.0分支

**Comment by Gumplefik** [comment]
部分buildpack master分支无法使用，例如 heroku-buildpack-nodejs 代码仓，检测失败导致nodejs项目unable to select a buildpack
5.0分支builder以及相关buildpack是否兼容3.7平台？

**Comment by ysicing** [comment]
5.0分支不兼容3.7平台，底层有所调整。可以参考3.7分支。如有部分无法正常使用，请调整buildpack 如nodejs历史版本为heroku-buildpack-nodejs-backports。稍后会修复这个问题

**Comment by ysicing** [comment]
@Gumplefik  你可以参考3.7.2分支

**Comment by Gumplefik** [comment]
@ysicing 已经打包builder完成。
最近改了nodejs的buildpack，有个问题，heroku-buildpack-nodejs项目里/lib/binaries.sh安装依赖时:
很多nodejs项目声明的node版本为  >=*.*.*   ,即${version}为该值，但构建时该类声明会直接使用最新版node，可是考虑使用sed得到版本号，默认安装最低，10.12.0版本的node无论5.0还是3.7都无法支持。其他同理。

**Comment by ysicing** [comment]
目前来看，确实有这样的问题，可以考虑对此的支持，目前的版本支持后续会与https://nodebin.herokai.com/
nodejs取版本 `cat package.json | jq --raw-output ".engines.node // \"\""`，默认8.x
可以一起探讨一下

**Comment by Gumplefik** [comment]
@ysicing 基于3.7版本builder，我是通过如下方式重新处理${version}的,去除其中的特殊符号:
local version=$(echo ${version}| sed 's/[=~><]*\(.*\)/\1/g')
默认取右侧值，但是考虑到值的前后可能会有空格，修改后
local version=$(echo ${version}| sed 's/[ =~><]*\(.*\) *$/\1/g')
究竟是再compile中处理该值还是binaries中处理看自己的选择.。
上面的方案还不够完善，实际情况${version}取值有如下情况：
>=8.9.4           >8.9.4             
极端情况：
<=8.9.4           <8.9.4
统一一点还是只考虑>=8.9.4  与 >8.9.4两种情况，然后就需要额外判断了

**Comment by Gumplefik** [comment]
@ysicing 早上回复时忘记标识code，shell脚本有些字符转义丢失了，如果你有使用，需要重新复制一下
